### ISSUE TITLE
获取人物图片是，服务器内部错误

### ISSUE THREAD

**Issue by li-guohao** [xjasonlyu/avdc-api#10]
# 描述
我在配置好jellyfin后，封面等其它信息获取正常，但是人物封面图获取错误，下面是日志

# 环境
- jellfyin10.7.7
- avdc-api版本我不知道，我是直接照着那个文档拉起的这个docker镜像:`ghcr.io/xjasonlyu/avdc-api`, 那个DB文件也是在那个文档里的链接下载的，链接地址：[Docker安装（推荐）](https://github.com/xjasonlyu/avdc-api/wiki/Docker%E5%AE%89%E8%A3%85%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89)

# avdc-api日志
```


[2021-11-20 14:47:53,543] ERROR in app: Exception on /image/actress/相沢みなみ/0 [GET]


Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/server/views.py", line 100, in _actress_image
    image.autoCropImage(
  File "/app/avdc/utility/image.py", line 123, in autoCropImage
    faces = findFaces(img)
  File "/app/avdc/utility/image.py", line 74, in findFaces
    for face in detect_faces(imageToBytes(img))]
  File "/app/avdc/utility/face_api.py", line 10, in detect_faces
    client = vision.ImageAnnotatorClient()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision_v1/services/image_annotator/client.py", line 362, in __init__
    self._transport = Transport(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision_v1/services/image_annotator/transports/grpc.py", line 154, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision_v1/services/image_annotator/transports/base.py", line 109, in __init__
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 464, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 457, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 226, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 110, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File /key.json was not found.
10.0.3.3 - - [20/Nov/2021 14:47:53] "GET /image/actress/相沢みなみ/0 HTTP/1.1" 500 - 
```

# jellyfin日志
``` 
2021-11-20T14:47:52.081771736Z [22:47:52] [INF] [66] Jellyfin.Plugin.AVDC.Providers.ActressProvider: [AVDC] GetMetadata for actress: 相沢みなみ
2021-11-20T14:47:52.136067122Z [22:47:52] [INF] [6] Jellyfin.Plugin.AVDC.Providers.ActressImageProvider: [AVDC] GetImages for actress: 相沢みなみ
2021-11-20T14:47:53.546486543Z [22:47:53] [WRN] [66] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from http://192.168.2.229:8900/image/actress/相沢みなみ/0. Http status code: InternalServerError
2021-11-20T14:47:53.546521411Z System.Net.Http.HttpRequestException: Invalid image received.
2021-11-20T14:47:53.546528964Z    at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
2021-11-20T14:47:53.546535864Z    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
2021-11-20T14:47:53.546542378Z    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

**Comment by huxim** [comment]
我也遇到了,似乎是最新版需要一个key.json,但这个文件如何生成没有教程

**Comment by leeyonwang** [comment]
> 我也遇到了,似乎是最新版需要一个key.json,但这个文件如何生成没有教程

搞定了 这大哥教程没写全
他在别的提问里甩了一个连接 https://cloud.google.com/vision/docs/setup 啥也没说 
其实就是照着前面这个连接 申请一个谷歌视觉的api 照着这个连接里的教程 最后你会得到一个密钥文件，json后缀的，然后就简单了，你把这个文件改名为key.json 放到docker你放avdc的文件夹里 然后把这个key.json文件在容器的设置里映射到/key.json  重启容器就行了。。很简单。。主要是大哥教程少写了一步。。

**Comment by huxim** [comment]
> 

我的账号始终无法开启结算,能否分享下你的key?huxim123gmail邮箱

**Comment by huxim** [comment]
> 

我的账号始终无法开启结算,能否分享下你的key?huxim123gmail邮箱

**Comment by huxim** [comment]
> > 我也遇到了,似乎是最新版需要一个key.json,但这个文件如何生成没有教程
> 
> 搞定了 这大哥教程没写全 他在别的提问里甩了一个连接 https://cloud.google.com/vision/docs/setup 啥也没说 其实就是照着前面这个连接 申请一个谷歌视觉的api 照着这个连接里的教程 最后你会得到一个密钥文件，json后缀的，然后就简单了，你把这个文件改名为key.json 放到docker你放avdc的文件夹里 然后把这个key.json文件在容器的设置里映射到/key.json 重启容器就行了。。很简单。。主要是大哥教程少写了一步。。
我的账号始终无法开启结算,能否分享下你的key?huxim123gmail邮箱

**Comment by huxim** [comment]
> > 我也遇到了,似乎是最新版需要一个key.json,但这个文件如何生成没有教程
> 
> 搞定了 这大哥教程没写全 他在别的提问里甩了一个连接 https://cloud.google.com/vision/docs/setup 啥也没说 其实就是照着前面这个连接 申请一个谷歌视觉的api 照着这个连接里的教程 最后你会得到一个密钥文件，json后缀的，然后就简单了，你把这个文件改名为key.json 放到docker你放avdc的文件夹里 然后把这个key.json文件在容器的设置里映射到/key.json 重启容器就行了。。很简单。。主要是大哥教程少写了一步。。

我的账号始终无法开启结算,能否分享下你的key?huxim123gmail邮箱
