### ISSUE TITLE
图片获取失败

### ISSUE THREAD

**Issue by lencshu** [xjasonlyu/avdc-api#4]
今天(29/05/2021)突然开始无法获取所有的封面图

request返回：
> {"message":"Invalid URL '/pics/cover/4oqg_b.jpg': No schema supplied. Perhaps you meant http:///pics/cover/4oqg_b.jpg?","status":false}

log日志:
~~~
[2021-05-29 21:21:24,858] ERROR in app: Exception on /image/primary/KUSE-006 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/server/api.py", line 38, in wrapper
    return fn(parseVID(vid)[0])
  File "/app/server/views.py", line 143, in _primary_image
    data = api.GetPrimaryImageByVID(vid)
  File "/app/server/api.py", line 242, in GetPrimaryImageByVID
    cover = GetBackdropImageByVID(vid, *args, **kwargs)
  File "/app/server/api.py", line 226, in GetBackdropImageByVID
    data = getRawImageByURL(cover_url, headers=headers or None)
  File "/app/avdc/utility/image.py", line 23, in getRawImageByURL
    return get_blob(url, raise_for_status=True, **kwargs)
  File "/app/avdc/utility/httpclient.py", line 103, in get_blob
    return get(url, **kwargs).content
  File "/app/avdc/utility/httpclient.py", line 95, in get
    return request('get', url, **kwargs)
  File "/app/avdc/utility/httpclient.py", line 80, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/pics/cover/83k6_b.jpg': No schema supplied. Perhaps you meant http:///pics/cover/83k6_b.jpg?
10.0.3.3 - - [29/May/2021 21:21:24] "GET /image/primary/KUSE-006 HTTP/1.1" 500 -
[2021-05-29 21:21:24,878] ERROR in app: Exception on /image/thumb/KUSE-006 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/server/api.py", line 38, in wrapper
    return fn(parseVID(vid)[0])
  File "/app/server/views.py", line 154, in _thumb_image
    data = api.GetThumbImageByVID(vid)
  File "/app/server/api.py", line 260, in GetThumbImageByVID
    cover = GetBackdropImageByVID(vid, *args, **kwargs)
  File "/app/server/api.py", line 226, in GetBackdropImageByVID
    data = getRawImageByURL(cover_url, headers=headers or None)
  File "/app/avdc/utility/image.py", line 23, in getRawImageByURL
    return get_blob(url, raise_for_status=True, **kwargs)
  File "/app/avdc/utility/httpclient.py", line 103, in get_blob
    return get(url, **kwargs).content
  File "/app/avdc/utility/httpclient.py", line 95, in get
    return request('get', url, **kwargs)
  File "/app/avdc/utility/httpclient.py", line 80, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/pics/cover/83k6_b.jpg': No schema supplied. Perhaps you meant http:///pics/cover/83k6_b.jpg?
10.0.3.3 - - [29/May/2021 21:21:24] "GET /image/thumb/KUSE-006 HTTP/1.1" 500 -`
~~~

**Comment by elizhyu** [comment]
相同的问题，个人具体版本号plugin插件`2021.524.1245.0`，api为docker hub的`latest`

**Comment by siryle** [comment]
我也遇到了，发现问题为javbus修改了封面的链接。目前链接为/pics/cover/8981_b.jpg，之前为https://www.javbus.com/pics/cover/8981_b.jpg，少了站点前缀。

**Comment by elizhyu** [comment]
> 相同的问题，补充说明一下**所有信息均刮削无误，但是所有封面刮削失败。**
> 
> 个人具体版本号plugin插件`2021.524.1245.0`，api为docker hub的`latest`

最新的 e0780d12d1a51436e3ab8eab1fc4c5481f39bf4e commit已修复该问题
